### ISSUE TITLE
OTS - Trip start date after 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1713] opened 2020-06-29 23:43 UTC
@sethgerou-noaa 

Here are screen shots of the start/end date issue.

![image](https://user-images.githubusercontent.com/31421964/86066030-e4004280-ba25-11ea-84cf-1aac69dfda6b.png)

![image](https://user-images.githubusercontent.com/31421964/86064300-997cc700-ba21-11ea-8e92-f2ba7fddbb52.png)

**Comment by sethgerou-noaa** [comment] 2020-07-02 19:35
Looks like the trip history is for the trip with valid dates (depart 6/25 - return 6/26) not the invalid one (6/23 - 6/22)
Unfortunately, the invalid one doesn't have a history - will try to reproduce.

**Comment by sethgerou-noaa** [comment] 2020-07-02 19:56
have not been able to reproduce - suggest we expand the number of people trying - discuss Monday.

**Comment by neilriley-NOAA** [comment] 2020-07-06 21:16
@sethgerou-noaa I have not been able to reproduce this either.

**Comment by sethgerou-noaa** [comment] 2020-07-07 23:51
haven't been able to reproduce - for now, chalking this up to trip entered before fix was applied, or cached outdated code allowing something that's not possible with the current code.  Closing for now - will re-open if this crops up again.

**Closed by sethgerou-noaa** 2020-07-07 23:51 UTC
Labels: bug, obs-web
