### ISSUE TITLE
Trips vessel select after role change shows 2 lines

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1632] opened 2020-06-03 18:40 UTC
![image](https://user-images.githubusercontent.com/45770674/83676142-12a60d00-a58f-11ea-818b-a7f05a902127.png)
@neilriley-NOAA 
@sethgerou-noaa

**Comment by sethgerou-noaa** [comment] 2020-06-08 23:18
this is by design - top one is what a captain sees (vessels the logged in user is assigned to), bottom is all available vessels.  

In your opinion, is this confusing for a staff person?  The alternative would be, if user has staff role, they only see the second dropdown (regardless of their assigned vessels) - does that sound better?

**Comment by sethgerou-noaa** [comment] 2020-06-11 16:10
@neilriley-NOAA @scottleach-NOAA @johnlafargue-noaa Currently when a staff member is in non-captain mode, they see dropdowns for their assigned vessels and all vessels on the trips page.  Are we happy with this, or in non-captain mode, should staff just see the dropdown for all vessels?

**Comment by sethgerou-noaa** [comment] 2020-06-16 15:27
@neilriley-NOAA @scottleach-NOAA @johnlafargue-noaa @ericbrasseur-NOAA 
Anyone care to weigh in on their preference on this? (Staff currently see assigned vessels and all vessels as 2 separate dropdowns on trips page when not in Captain Mode)  If not, I'll close the ticket and leave as is.

**Comment by ericbrasseur-NOAA** [comment] 2020-06-16 15:31
The view is very confusing. Both are shown as drop downs but only one works.  I had no idea at all what to make of it. It seems like somethings broken.  I would only show the drop down list that works and load the vessel selected.

**Comment by johnlafargue-noaa** [comment] 2020-06-16 15:33
I don’t think we need assigned vessels, just al vessels.

On Jun 16, 2020, at 8:32 AM, Eric Brasseur <notifications@github.com> wrote:

﻿

The view is very confusing. Both are shown as drop downs but only one
works. I had no idea at all what to make of it. It seems like somethings
broken. I would only show the drop down list that works and load the vessel
selected.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nwfsc-fram/boatnet/issues/1632#issuecomment-644840233>,
or unsubscribe

**Comment by sethgerou-noaa** [comment] 2020-06-16 15:39
ok thanks, I'll make it so.

**Comment by neilriley-NOAA** [comment] 2020-06-16 15:42
agreed. I don't think we need the assigned vessels.  In the end, staff will not be assigned as a captain, so staff will need to be able to simply select a vessel from the complete list of vessels and create a trip.

**Comment by sethgerou-noaa** [comment] 2020-06-16 23:19
switch to global search as in vessel managment

**Closed** 2020-06-22 17:26 UTC
Labels: Prj:OTS, obs-web
